
server {
	listen 127.0.0.10:9090;
	server_name localhost;
	root nginxApp/SimpleWebsite;
	error_page 401 402 403 404 500 cgi-bin/error.py

	location / {
		root nginxApp/SimpleWebsite;
		index static/index.html;
	}
	
	location /cgi-bin/ {
		cgi on;
        cgi_pass .py;
	}

	location /cgi-bin/uploads/ {
		autoindex on;
		limit_except DELETE {
            deny all;
        }
	}

	location /static/ {
		autoindex on;
		limit_except GET {
            deny all;
        }
	}
	
	location /redirect {
        # Redirection
        return http://127.0.0.1:8080/static/index.html; #code de retour
    }

	location /static/upload.html {
        upload_enable on;
        upload_store /www/cgi-bin/uploads/;
        limit_except GET POST {
            deny all;
        }
    }

}

