
server {
	listen 127.0.0.1:9090;
	server_name localhost;
	root nginxApp/SimpleWebsite/;
	# error_page 401 402 403 404 500 cgi-bin/error.py;

	location / {
		root nginxApp/SimpleWebsite/;
		index static/index.html;
	}
	
	location /cgi-bin/ {
		cgi on;
        cgi_pass .py;
	}

	location /images/ {
		autoindex on;
	}

	location /cgi-bin/uploads/ {
		autoindex on;
		limit_except POST {
            deny all;
        }
	}

	location /static/ {
		autoindex on;
		limit_except GET {
            deny all;
        }
	}
	
	location /redirection/ {
        # Redirection
        return http://127.0.0.1:9091/; #code de retour
    }

	location /static/upload.html {
        upload_enable on;
        upload_store /www/cgi-bin/uploads/;
        # limit_except GET POST {
        #     deny all;
        # }
    }

}

server {
	listen 127.0.0.1:9091;
	server_name redirhost;
	root nginxApp/SimpleWebsite/;
	# error_page 401 402 403 404 500 cgi-bin/error.py;

	location / {
		root nginxApp/SimpleWebsite/;
		index static/redirect.html;
	}

}

server {
	listen 127.0.0.1:9092;
	server_name unallowMethodshost;
	root nginxApp/SimpleWebsite/;
	# error_page 401 402 403 404 500 cgi-bin/error.py;

	location / {
		root nginxApp/SimpleWebsite/;
		index static/index.html;
	}
	
	# on peut voir les ressources upload mais pas en televerser de nouvelles
	location /cgi-bin/uploads/ {
		autoindex on; 
		limit_except GET {
            deny all;
        }
	}

	# on peut delete les images de la liste mais pas les voir
	location /images/ {
		limit_except DELETE {deny all} 
	}

}